function sortAlphabetically(values) {
  return [...values].sort((left, right) => left.localeCompare(right, undefined, { sensitivity: 'base' }));
}

export const PRESET_GENRES = sortAlphabetically([
  'Fantasy',
  'Sci-Fi',
  'Mystery',
  'Thriller',
  'Romance',
  'Horror',
  'Adventure',
  'Historical',
  'Action',
  'Slice of Life',
  'Erotica',
  'Crime',
  'Comedy',
  'Drama',
  'Dystopian',
  'Supernatural',
  'Urban Fantasy',
  'Dark Fantasy',
  'Mythic Fantasy',
  'Sword and Sorcery',
  'Political Fantasy',
  'Literary Fiction',
]);

export const PRESET_THEMES = sortAlphabetically([
  'Coming of Age',
  'Revenge',
  'Redemption',
  'Sacrifice',
  'Identity',
  'Fate',
  'Betrayal',
  'Survival',
  'Love',
  'Obsession',
  'Ambition',
  'Power',
  'Corruption',
  'Justice',
  'Freedom',
  'Duty',
  'Hope',
  'Despair',
  'Grief',
  'Healing',
  'Faith',
  'Doubt',
  'Belonging',
  'Isolation',
  'Transformation',
  'Legacy',
  'Memory',
  'Truth',
  'Forgiveness',
  'Forbidden Love',
  'Class Struggle',
  'Found Family',
  'Mortality',
  'Colonization',
  'Humanity',
  'Alienation',
]);

export const PRESET_CUSTOM_TAGS = sortAlphabetically([
  'medieval',
  'human-centric',
  'industrial',
  'female protagonist',
  'male protagonist',
  'magic-system',
  'steampunk',
  'cyberpunk',
  'high-fantasy',
  'grimdark',
  'gothic',
  'erotic',
  'slow-burn',
  'modern day',
  'ancient',
  'prehistoric',
  'victorian',
  'colonial',
  'western',
  'wartime',
  'retrofuturistic',
  'post-apocalyptic',
  'post-collapse',
  'near-future',
  'far-future',
  'spacefaring',
  'globetrotting',
  'frontier',
  'urban',
  'rural',
  'isolated',
  'underground',
  'underwater',
  'zero gravity',
  'low gravity',
  'floating city',
  'megacity',
  'small town',
  'single location',
  'time pressure',
  'road trip',
  'alternate history',
  'alternate world',
  'parallel worlds',
  'dying world',
  'lost civilization',
  'ruins',
  'low technology',
  'advanced technology',
  'artificial intelligence',
  'transhumanism',
  'cybernetics',
  'cyborgs',
  'androids',
  'robots',
  'clockwork',
  'alchemy',
  'gunpowder',
  'rare magic',
  'common magic',
  'hard magic',
  'soft magic',
  'no magic',
  'low-fantasy',
  'hard sci-fi',
  'soft sci-fi',
  'faster than light',
  'ensemble cast',
  'antihero',
  'dialogue heavy',
  'no dialogue',
  'dialogue light',
  'grounded',
  'realistic',
  'surreal',
  'dreamlike',
  'hopeful',
  'bleak',
  'low-stakes',
  'high-stakes',
  'cozy',
  'intimate',
  'political intrigue',
  'court intrigue',
  'forbidden romance',
  'found family',
  'morally gray',
  'chosen one',
  'heist',
  'monster hunting',
  'survivalist',
  'science fantasy',
  'eldritch',
  'body horror',
  'folk horror',
  'academia',
  'military',
  'naval',
  'wilderness',
  'religious order',
  'sex',
  'nsfw',
  'violence',
  'war',
  'gifted individual',
  'supernatural abilities',
  'superpowers',
  'mutants',
  'the beauty of struggle',
]);

export const PRESET_CHARACTER_TAGS = sortAlphabetically([
  'adult',
  'ambitious',
  'android',
  'aristocratic',
  'athletic',
  'awkward',
  'bald',
  'bangs',
  'bearded',
  'black hair',
  'blonde',
  'blue eyes',
  'bookish',
  'broad-shouldered',
  'brown eyes',
  'brunette',
  'calm',
  'charismatic',
  'cheerful',
  'child',
  'charming',
  'cunning',
  'curly hair',
  'cyborg',
  'determined',
  'dutiful',
  'elegant',
  'elderly',
  'female',
  'freckles',
  'gentle',
  'gifted',
  'gray eyes',
  'guarded',
  'green eyes',
  'gruff',
  'hazel eyes',
  'idealistic',
  'impulsive',
  'kind',
  'lean',
  'male',
  'mischievous',
  'mysterious',
  'nonbinary',
  'observant',
  'older',
  'optimistic',
  'pale',
  'quiet',
  'reckless',
  'red hair',
  'reserved',
  'robotic',
  'sarcastic',
  'scarred',
  'shaved head',
  'shy',
  'silver hair',
  'slender',
  'stoic',
  'straight hair',
  'stern',
  'streetwise',
  'strong',
  'tall',
  'tattoos',
  'teen',
  'timid',
  'tired eyes',
  'wavy hair',
  'white hair',
  'young adult',
  'flat chest',
  'large breasts',
  'small breasts',
  'gigantic breasts',
  'micropenis',
  'small penis',
  'large penis',
  'gigantic penis',
  'glasses',
  'dark hair',
]);

function clampSelectionCount(length, min, max) {
  if (length === 0) {
    return 0;
  }

  const minCount = Math.max(1, min);
  const maxCount = Math.max(minCount, max);
  const targetCount = Math.floor(Math.random() * (maxCount - minCount + 1)) + minCount;
  return Math.min(length, targetCount);
}

export function pickRandomPresets(presets, { min = 1, max = 1 } = {}) {
  const uniquePresets = [...new Set(presets)];
  const shuffledPresets = [...uniquePresets].sort(() => Math.random() - 0.5);
  const selectionCount = clampSelectionCount(shuffledPresets.length, min, max);

  return sortAlphabetically(shuffledPresets.slice(0, selectionCount));
}

export function sortPresetSelection(values) {
  return sortAlphabetically([...new Set(values)]);
}
